### ISSUE TITLE
Styling does not "pop" enough.

### ISSUE THREAD

**Issue by khalidwilliams** [hannahhch/github-cheatsheet#3]
@hannahhch This page looks great, but I think we need more vibrant colors. It should be painful on the eyes. We need WAY higher contrast. More saturation. Broadway fonts. 

<img width="408" alt="Screen Shot 2020-02-04 at 3 47 23 PM" src="https://user-images.githubusercontent.com/36432040/73961648-3e0f3880-48ca-11ea-9679-919ea4afb6bb.png">

Can we work on this?

**Comment by hannahhch** [comment]
Okay I do think it could be more colorful but this seems extreme. I will work on this and get back to you! @khalidwilliams
